server:
  port: 10000

spring:
  application:
    name: gateway-1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: GATEWAY_GROUP
        namespace: 7a552eec-cda7-41d5-b020-f73e8d3b8609
      password: nacos
      username: nacos
    gateway:
      routes:
        - id: oneCoupon-merchant-admin
          uri: lb://user-service
          predicates:
            - Path=/api/user/**